In [1]:
import pandas as pd
from tqdm import tqdm

In [2]:
df_1 = pd.read_csv('./result/patent_sim_1.csv')
df_1.head()

  citing_patent_id  cited_patent_id  similarity            category
0          5093563         10000000       0.619   cited by examiner
1          5751830         10000000       0.675  cited by applicant
2          7804268         10000001       0.695   cited by examiner
3          9022767         10000001       0.788   cited by examiner
4          9090016         10000001       0.673   cited by examiner

In [3]:
df_2 = pd.read_csv('./result/patent_sim_2.csv')
df_2.head()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_14204\4273957585.py:1: DtypeWarning: Columns (0,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2 = pd.read_csv('./result/patent_sim_2.csv')

  citing_patent_id  cited_patent_id  similarity category
0          8001969          3931976       0.443      NaN
1          3987991          3935991       0.374      NaN
2          5857301          3943789       0.426      NaN
3          3998395          3944004       0.486      NaN
4          3989790          3945191       0.180      NaN

In [4]:
df_3 = pd.read_csv('./result/patent_sim_3.csv')
df_3.head()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_14204\882821496.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_3 = pd.read_csv('./result/patent_sim_3.csv')

  citing_patent_id cited_patent_id  similarity           category
0          6299329         8294741       0.449     cited by other
1          6326981         8294741       0.519     cited by other
2          6327008         8294741       0.446  cited by examiner
3          6332030         8294741       0.333     cited by other
4          6348929         8294741       0.325     cited by other

#### Step 合并

In [6]:
merged_df = pd.concat([df_1, df_2, df_3], axis=0, ignore_index=True)

In [7]:
merged_df

          citing_patent_id cited_patent_id  similarity            category
0                  5093563        10000000       0.619   cited by examiner
1                  5751830        10000000       0.675  cited by applicant
2                  7804268        10000001       0.695   cited by examiner
3                  9022767        10000001       0.788   cited by examiner
4                  9090016        10000001       0.673   cited by examiner
...                    ...             ...         ...                 ...
113575658          9787457         RE50356       0.583   cited by examiner
113575659         10164689         RE50356       0.664   cited by examiner
113575660         10652955         RE50356       1.000  cited by applicant
113575661          8431969         RE50357       0.811  cited by applicant
113575662          8811082         RE50357       0.759  cited by applicant

[113575663 rows x 4 columns]

In [8]:
df_unique = merged_df.drop_duplicates()

In [12]:
df_unique.to_csv('./result/p2p_reference.sim.csv',index=False)

In [11]:
summary = df_unique.groupby('category')['similarity'].agg(['mean', 'count', 'std']).reset_index()
print(summary)

                              category      mean     count       std
0                   cited by applicant  0.511495  57750958  0.123238
1                    cited by examiner  0.568943  19432006  0.122783
2                       cited by other  0.529481  22012753  0.119031
3                 cited by third party  0.557245      3852  0.123528
4  imported from a related application  0.512527     22949  0.114592